// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYlYBBiQ-QKgtQM762W3JIDcLQVKYXlbQ',
    appId: '1:979867775834:web:0155596127f0425d96f963',
    messagingSenderId: '979867775834',
    projectId: 'vgompa-cmsc5303-flutter',
    authDomain: 'vgompa-cmsc5303-flutter.firebaseapp.com',
    storageBucket: 'vgompa-cmsc5303-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Yfz_fMiek55HLMsOIGZf6vm0W4RmFzg',
    appId: '1:979867775834:android:17ee2db7f99888c796f963',
    messagingSenderId: '979867775834',
    projectId: 'vgompa-cmsc5303-flutter',
    storageBucket: 'vgompa-cmsc5303-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv9IZL6KxiRVdemYwmkHW2hO87iK4rK5Y',
    appId: '1:979867775834:ios:a2c08daa44a041ab96f963',
    messagingSenderId: '979867775834',
    projectId: 'vgompa-cmsc5303-flutter',
    storageBucket: 'vgompa-cmsc5303-flutter.firebasestorage.app',
    iosBundleId: 'edu.uco.vgompa.cmsc5303.lesson6',
  );

}